### ISSUE TITLE
installing the package

### ISSUE THREAD

**Issue by naarkhoo** [realead/cykhash#5]
I am trying to install the package through 
`pip install https://github.com/realead/cykhash/zipball/master` but I get the following error

```
pip install https://github.com/realead/cykhash/zipball/master
Collecting https://github.com/realead/cykhash/zipball/master
  Using cached https://github.com/realead/cykhash/zipball/master
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/opt/anaconda3/bin/python /Users/opt/anaconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/lq/1jmltv0s01xgkhn9y4dktbl40000gn/T/pip-build-env-ummh3bsl/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28'
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "/Users/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Users/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/opt/anaconda3/lib/python3.7/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/Users/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/Users/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/Users/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/Users/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/Users/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.collector import LinkCollector
    File "/Users/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/Users/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 125, in <module>
      from . import utils
    File "/Users/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/Users/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/Users/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/Users/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "/Users/opt/anaconda3/lib/python3.7/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/Users/opt/anaconda3/lib/python3.7/site-packages/typing.py", line 1357, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/Users/opt/anaconda3/lib/python3.7/site-packages/typing.py", line 1005, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/opt/anaconda3/bin/python /Users/opt/anaconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/lq/1jmltv0s01xgkhn9y4dktbl40000gn/T/pip-build-env-ummh3bsl/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28' Check the logs for full command output.
```

I have Cython==0.29.13 and using Python 3.7.4
I appreciate any hint

**Comment by realead** [comment]
@naarkhoo There seems to be something wrong with your python-installation. During the setup, the wrong version of `typing.py` is picked up:

Instead of `/Users/opt/anaconda3/lib/python3.7/site-packages/typing.py`, which is from https://pypi.org/project/typing/, `/Users/opt/anaconda3/lib/python3.7/typing.py` (which is the built-in version, see https://docs.python.org/3/library/typing.html) should be used. In Python3.7 they are not the same.

Normally, stdlib comes before site-packages, so it shouldn't be a problem to have a shadow version. However, in your case either the `sys.path` has wrong order or maybe during the installation `site-packages` will be picked up before stdlib.

Check that there is a built-in version of typing.py and uninstall the installed version from `site-packages`.

**Comment by naarkhoo** [comment]
Thank you for your quick response.
I just did `pip uninstall typing ` and it got further but I am getting a different error,

```
  ERROR: Command errored out with exit status 1:
   command: /Users/opt/anaconda3/bin/python /Users/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/lq/1jmltv0s01xgkhn9y4dktbl40000gn/T/tmpx9uylt30
       cwd: /private/var/folders/lq/1jmltv0s01xgkhn9y4dktbl40000gn/T/pip-install-f4tad3p9/cykhash
  Complete output (81 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/cykhash
  copying src/cykhash/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/cykhash
  running egg_info
  writing src/cykhash.egg-info/PKG-INFO
  writing dependency_links to src/cykhash.egg-info/dependency_links.txt
  writing top-level names to src/cykhash.egg-info/top_level.txt
  reading manifest file 'src/cykhash.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'src/cykhash.egg-info/SOURCES.txt'
  copying src/cykhash/float_utils.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash
  copying src/cykhash/floatdef.pxd -> build/lib.macosx-10.9-x86_64-3.7/cykhash
  copying src/cykhash/khash.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash
  copying src/cykhash/khashmaps.pxd -> build/lib.macosx-10.9-x86_64-3.7/cykhash
  copying src/cykhash/khashmaps.pyx -> build/lib.macosx-10.9-x86_64-3.7/cykhash
  copying src/cykhash/khashsets.pxd -> build/lib.macosx-10.9-x86_64-3.7/cykhash
  copying src/cykhash/khashsets.pyx -> build/lib.macosx-10.9-x86_64-3.7/cykhash
  copying src/cykhash/pyobject_utils.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash
  copying src/cykhash/unique.pxd -> build/lib.macosx-10.9-x86_64-3.7/cykhash
  copying src/cykhash/unique.pyx -> build/lib.macosx-10.9-x86_64-3.7/cykhash
  creating build/lib.macosx-10.9-x86_64-3.7/cykhash/maps
  creating build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/float32
  copying src/cykhash/maps/float32/float32to32map_header.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/float32
  copying src/cykhash/maps/float32/float32to32map_impl.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/float32
  copying src/cykhash/maps/float32/init_float32to32map.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/float32
  creating build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/float64
  copying src/cykhash/maps/float64/float64to64map_header.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/float64
  copying src/cykhash/maps/float64/float64to64map_impl.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/float64
  copying src/cykhash/maps/float64/init_float64to64map.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/float64
  creating build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/int32
  copying src/cykhash/maps/int32/init_int32to32map.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/int32
  copying src/cykhash/maps/int32/int32to32map_header.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/int32
  copying src/cykhash/maps/int32/int32to32map_impl.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/int32
  creating build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/int64
  copying src/cykhash/maps/int64/init_int64to64map.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/int64
  copying src/cykhash/maps/int64/int64to64map_header.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/int64
  copying src/cykhash/maps/int64/int64to64map_impl.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/int64
  creating build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/pyobject
  copying src/cykhash/maps/pyobject/init_pyobjectmap.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/pyobject
  copying src/cykhash/maps/pyobject/pyobjectmap_header.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/pyobject
  copying src/cykhash/maps/pyobject/pyobjectmap_impl.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/maps/pyobject
  creating build/lib.macosx-10.9-x86_64-3.7/cykhash/sets
  creating build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/float32
  copying src/cykhash/sets/float32/float32set_header.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/float32
  copying src/cykhash/sets/float32/float32set_impl.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/float32
  copying src/cykhash/sets/float32/init_float32set.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/float32
  creating build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/float64
  copying src/cykhash/sets/float64/float64set_header.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/float64
  copying src/cykhash/sets/float64/float64set_impl.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/float64
  copying src/cykhash/sets/float64/init_float64set.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/float64
  creating build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/int32
  copying src/cykhash/sets/int32/init_int32set.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/int32
  copying src/cykhash/sets/int32/int32set_header.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/int32
  copying src/cykhash/sets/int32/int32set_impl.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/int32
  creating build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/int64
  copying src/cykhash/sets/int64/init_int64set.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/int64
  copying src/cykhash/sets/int64/int64set_header.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/int64
  copying src/cykhash/sets/int64/int64set_impl.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/int64
  creating build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/pyobject
  copying src/cykhash/sets/pyobject/init_pyobjectset.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/pyobject
  copying src/cykhash/sets/pyobject/pyobjectset_header.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/pyobject
  copying src/cykhash/sets/pyobject/pyobjectset_impl.pxi -> build/lib.macosx-10.9-x86_64-3.7/cykhash/sets/pyobject
  running build_ext
  building 'cykhash.khashsets' extension
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/src
  creating build/temp.macosx-10.9-x86_64-3.7/src/cykhash
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/opt/anaconda3/include -arch x86_64 -I/Users/opt/anaconda3/include -arch x86_64 -I/usr/local/opt/llvm/include -I/Users/opt/anaconda3/include/python3.7m -c src/cykhash/khashsets.c -o build/temp.macosx-10.9-x86_64-3.7/src/cykhash/khashsets.o
  In file included from /usr/local/Cellar/gcc/9.2.0_1/lib/gcc/9/gcc/x86_64-apple-darwin15/9.2.0/include-fixed/syslimits.h:7,
                   from /usr/local/Cellar/gcc/9.2.0_1/lib/gcc/9/gcc/x86_64-apple-darwin15/9.2.0/include-fixed/limits.h:34,
                   from /Users/opt/anaconda3/include/python3.7m/Python.h:11,
                   from src/cykhash/khashsets.c:17:
  /usr/local/Cellar/gcc/9.2.0_1/lib/gcc/9/gcc/x86_64-apple-darwin15/9.2.0/include-fixed/limits.h:194:15: fatal error: limits.h: No such file or directory
    194 | #include_next <limits.h>  /* recurse down to the real one */
        |               ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cykhash

```

I am running it through conda - do you happen know what is needed ? sorry that this threat getting to a different direction.

**Comment by realead** [comment]
It looks as if you are missing (the right) `libc-dev`. But not so sure, as I have next to no experience with macOS: normally installing `build-essential` gets everything what is needed (`gcc` with `libc-dev`) on linux.

**Comment by naarkhoo** [comment]
Thanks - 
seems it is under openssl in Mac - based on the discussion https://superuser.com/questions/1089390/how-to-install-libssl-dev-libffi-dev-on-mac-os I repaired my openssl and now works ! I look forward using the package. Thank you again.
